### ISSUE TITLE
4.0.5无法登录

### ISSUE THREAD

**Issue by Glucy-2** [Coloryr/ColorMirai#15]
已经用MiraiAndroid提取device.json
botlog里面没有验证码
config.json:
````json
{
	"autoReconnect":true,
	"cacheSize":100,
	"debug":false,
	"escapeSelf":true,
	"highwayUpload":10,
	"maxList":100000,
	"maxNettyPackSize":500,
	"nettyPort":23335,
	"noInput":false,
	"pack":true,
	"qqList":[
		{
			"info":"device.json",
			"loginType":0,
			"password":"*****",
			"qq":****
		}
	],
	"readEncoding":"UTF-8",
	"sendEncoding":"UTF-8",
	"socketPort":23333,
	"webSocketPort":23334
}
````
日志：
````java
[00:39:47.380][INFO]如果登录卡住，去看看BotLog文件夹里面的日志有没有验证码
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
[00:40:07.906][ERROR]机器人错误 kotlinx.coroutines.JobCancellationException: Parent job is Cancelling
Caused by: java.net.UnknownHostException: msfwifi.3g.qq.com: Temporary failure in name resolution
        at java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method) ~[?:?]
        at java.net.InetAddress$PlatformNameService.lookupAllHostAddr(InetAddress.java:933) ~[?:?]
        at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1519) ~[?:?]
        at java.net.InetAddress$NameServiceAddresses.get(InetAddress.java:852) ~[?:?]
        at java.net.InetAddress.getAllByName0(InetAddress.java:1509) ~[?:?]
        at java.net.InetAddress.getAllByName(InetAddress.java:1367) ~[?:?]
        at java.net.InetAddress.getAllByName(InetAddress.java:1301) ~[?:?]
        at java.net.InetAddress.getByName(InetAddress.java:1251) ~[?:?]
        at io.netty.util.internal.SocketUtils$8.run(SocketUtils.java:156) ~[ColorMirai-4.0.5-all.jar:?]
        at io.netty.util.internal.SocketUtils$8.run(SocketUtils.java:153) ~[ColorMirai-4.0.5-all.jar:?]
        at java.security.AccessController.doPrivileged(AccessController.java:569) ~[?:?]
        at io.netty.util.internal.SocketUtils.addressByName(SocketUtils.java:153) ~[ColorMirai-4.0.5-all.jar:?]
        at io.netty.resolver.DefaultNameResolver.doResolve(DefaultNameResolver.java:41) ~[ColorMirai-4.0.5-all.jar:?]
        at io.netty.resolver.SimpleNameResolver.resolve(SimpleNameResolver.java:61) ~[ColorMirai-4.0.5-all.jar:?]
        at io.netty.resolver.SimpleNameResolver.resolve(SimpleNameResolver.java:53) ~[ColorMirai-4.0.5-all.jar:?]
        at io.netty.resolver.InetSocketAddressResolver.doResolve(InetSocketAddressResolver.java:55) ~[ColorMirai-4.0.5-all.jar:?]
        at io.netty.resolver.InetSocketAddressResolver.doResolve(InetSocketAddressResolver.java:31) ~[ColorMirai-4.0.5-all.jar:?]
        at io.netty.resolver.AbstractAddressResolver.resolve(AbstractAddressResolver.java:106) ~[ColorMirai-4.0.5-all.jar:?]
        at io.netty.bootstrap.Bootstrap.doResolveAndConnect0(Bootstrap.java:206) ~[ColorMirai-4.0.5-all.jar:?]
        at io.netty.bootstrap.Bootstrap.access$000(Bootstrap.java:46) ~[ColorMirai-4.0.5-all.jar:?]
        at io.netty.bootstrap.Bootstrap$1.operationComplete(Bootstrap.java:180) ~[ColorMirai-4.0.5-all.jar:?]
        at io.netty.bootstrap.Bootstrap$1.operationComplete(Bootstrap.java:166) ~[ColorMirai-4.0.5-all.jar:?]
        at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:578) ~[ColorMirai-4.0.5-all.jar:?]
        at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:552) ~[ColorMirai-4.0.5-all.jar:?]
        at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:491) ~[ColorMirai-4.0.5-all.jar:?]
        at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:616) ~[ColorMirai-4.0.5-all.jar:?]
        at io.netty.util.concurrent.DefaultPromise.setSuccess0(DefaultPromise.java:605) ~[ColorMirai-4.0.5-all.jar:?]
        at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:104) ~[ColorMirai-4.0.5-all.jar:?]
        at io.netty.channel.DefaultChannelPromise.trySuccess(DefaultChannelPromise.java:84) ~[ColorMirai-4.0.5-all.jar:?]
        at io.netty.channel.AbstractChannel$AbstractUnsafe.safeSetSuccess(AbstractChannel.java:990) ~[ColorMirai-4.0.5-all.jar:?]
        at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:516) ~[ColorMirai-4.0.5-all.jar:?]
        at io.netty.channel.AbstractChannel$AbstractUnsafe.access$200(AbstractChannel.java:429) ~[ColorMirai-4.0.5-all.jar:?]
        at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:486) ~[ColorMirai-4.0.5-all.jar:?]
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[ColorMirai-4.0.5-all.jar:?]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) ~[ColorMirai-4.0.5-all.jar:?]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[ColorMirai-4.0.5-all.jar:?]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:503) ~[ColorMirai-4.0.5-all.jar:?]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[ColorMirai-4.0.5-all.jar:?]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[ColorMirai-4.0.5-all.jar:?]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[ColorMirai-4.0.5-all.jar:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
        Suppressed: kotlinx.coroutines.JobCancellationException: Parent job is Cancelling
        Caused by: java.net.UnknownHostException: msfwifi.3g.qq.com: Temporary failure in name resolution
                at java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method) ~[?:?]
                at java.net.InetAddress$PlatformNameService.lookupAllHostAddr(InetAddress.java:933) ~[?:?]
                at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1519) ~[?:?]
                at java.net.InetAddress$NameServiceAddresses.get(InetAddress.java:852) ~[?:?]
                at java.net.InetAddress.getAllByName0(InetAddress.java:1509) ~[?:?]
                at java.net.InetAddress.getAllByName(InetAddress.java:1367) ~[?:?]
                at java.net.InetAddress.getAllByName(InetAddress.java:1301) ~[?:?]
                at java.net.InetAddress.getByName(InetAddress.java:1251) ~[?:?]
                at io.netty.util.internal.SocketUtils$8.run(SocketUtils.java:156) ~[ColorMirai-4.0.5-all.jar:?]
                at io.netty.util.internal.SocketUtils$8.run(SocketUtils.java:153) ~[ColorMirai-4.0.5-all.jar:?]
                at java.security.AccessController.doPrivileged(AccessController.java:569) ~[?:?]
                at io.netty.util.internal.SocketUtils.addressByName(SocketUtils.java:153) ~[ColorMirai-4.0.5-all.jar:?]
                at io.netty.resolver.DefaultNameResolver.doResolve(DefaultNameResolver.java:41) ~[ColorMirai-4.0.5-all.jar:?]
                at io.netty.resolver.SimpleNameResolver.resolve(SimpleNameResolver.java:61) ~[ColorMirai-4.0.5-all.jar:?]
                at io.netty.resolver.SimpleNameResolver.resolve(SimpleNameResolver.java:53) ~[ColorMirai-4.0.5-all.jar:?]
                at io.netty.resolver.InetSocketAddressResolver.doResolve(InetSocketAddressResolver.java:55) ~[ColorMirai-4.0.5-all.jar:?]
                at io.netty.resolver.InetSocketAddressResolver.doResolve(InetSocketAddressResolver.java:31) ~[ColorMirai-4.0.5-all.jar:?]
                at io.netty.resolver.AbstractAddressResolver.resolve(AbstractAddressResolver.java:106) ~[ColorMirai-4.0.5-all.jar:?]
                at io.netty.bootstrap.Bootstrap.doResolveAndConnect0(Bootstrap.java:206) ~[ColorMirai-4.0.5-all.jar:?]
                at io.netty.bootstrap.Bootstrap.access$000(Bootstrap.java:46) ~[ColorMirai-4.0.5-all.jar:?]
                at io.netty.bootstrap.Bootstrap$1.operationComplete(Bootstrap.java:180) ~[ColorMirai-4.0.5-all.jar:?]
                at io.netty.bootstrap.Bootstrap$1.operationComplete(Bootstrap.java:166) ~[ColorMirai-4.0.5-all.jar:?]
                at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:578) ~[ColorMirai-4.0.5-all.jar:?]
                at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:552) ~[ColorMirai-4.0.5-all.jar:?]
                at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:491) ~[ColorMirai-4.0.5-all.jar:?]
                at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:616) ~[ColorMirai-4.0.5-all.jar:?]
                at io.netty.util.concurrent.DefaultPromise.setSuccess0(DefaultPromise.java:605) ~[ColorMirai-4.0.5-all.jar:?]
                at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:104) ~[ColorMirai-4.0.5-all.jar:?]
                at io.netty.channel.DefaultChannelPromise.trySuccess(DefaultChannelPromise.java:84) ~[ColorMirai-4.0.5-all.jar:?]
                at io.netty.channel.AbstractChannel$AbstractUnsafe.safeSetSuccess(AbstractChannel.java:990) ~[ColorMirai-4.0.5-all.jar:?]
                at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:516) ~[ColorMirai-4.0.5-all.jar:?]
                at io.netty.channel.AbstractChannel$AbstractUnsafe.access$200(AbstractChannel.java:429) ~[ColorMirai-4.0.5-all.jar:?]
                at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:486) ~[ColorMirai-4.0.5-all.jar:?]
                at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[ColorMirai-4.0.5-all.jar:?]
                at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) ~[ColorMirai-4.0.5-all.jar:?]
                at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[ColorMirai-4.0.5-all.jar:?]
                at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:503) ~[ColorMirai-4.0.5-all.jar:?]
                at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[ColorMirai-4.0.5-all.jar:?]
                at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[ColorMirai-4.0.5-all.jar:?]
                at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[ColorMirai-4.0.5-all.jar:?]
                at java.lang.Thread.run(Thread.java:833) ~[?:?]
                Suppressed: java.util.concurrent.CancellationException: Bot closed
                        at kotlinx.coroutines.ExceptionsKt.CancellationException(Exceptions.kt:22) ~[ColorMirai-4.0.5-all.jar:?]
                        at net.mamoe.mirai.internal.AbstractBot.close(AbstractBot.kt:112) ~[ColorMirai-4.0.5-all.jar:?]
                        at net.mamoe.mirai.internal.QQAndroidBot.close(QQAndroidBot.kt:84) ~[ColorMirai-4.0.5-all.jar:?]
                        at net.mamoe.mirai.internal.AbstractBot.login(AbstractBot.kt:136) ~[ColorMirai-4.0.5-all.jar:?]
                        at net.mamoe.mirai.internal.AbstractBot$login$1.invokeSuspend(AbstractBot.kt) ~[ColorMirai-4.0.5-all.jar:?]
                        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) ~[ColorMirai-4.0.5-all.jar:?]
                        at kotlinx.coroutines.DispatchedTaskKt.resume(DispatchedTask.kt:178) ~[ColorMirai-4.0.5-all.jar:?]
                        at kotlinx.coroutines.DispatchedTaskKt.dispatch(DispatchedTask.kt:166) ~[ColorMirai-4.0.5-all.jar:?]
                        at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(CancellableContinuationImpl.kt:397) ~[ColorMirai-4.0.5-all.jar:?]
                        at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl(CancellableContinuationImpl.kt:431) ~[ColorMirai-4.0.5-all.jar:?]
                        at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl$default(CancellableContinuationImpl.kt:420) ~[ColorMirai-4.0.5-all.jar:?]
                        at kotlinx.coroutines.CancellableContinuationImpl.resumeWith(CancellableContinuationImpl.kt:328) ~[ColorMirai-4.0.5-all.jar:?]
                        at kotlinx.coroutines.ResumeAwaitOnCompletion.invoke(JobSupport.kt:1408) ~[ColorMirai-4.0.5-all.jar:?]
                        at kotlinx.coroutines.JobSupport.notifyCompletion(JobSupport.kt:1519) ~[ColorMirai-4.0.5-all.jar:?]
                        at kotlinx.coroutines.JobSupport.completeStateFinalization(JobSupport.kt:323) ~[ColorMirai-4.0.5-all.jar:?]
                        at kotlinx.coroutines.JobSupport.finalizeFinishingState(JobSupport.kt:240) ~[ColorMirai-4.0.5-all.jar:?]
                        at kotlinx.coroutines.JobSupport.tryMakeCompletingSlowPath(JobSupport.kt:906) ~[ColorMirai-4.0.5-all.jar:?]
                        at kotlinx.coroutines.JobSupport.tryMakeCompleting(JobSupport.kt:863) ~[ColorMirai-4.0.5-all.jar:?]
                        at kotlinx.coroutines.JobSupport.makeCompletingOnce$kotlinx_coroutines_core(JobSupport.kt:828) ~[ColorMirai-4.0.5-all.jar:?]
                        at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:100) ~[ColorMirai-4.0.5-all.jar:?]
                        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46) ~[ColorMirai-4.0.5-all.jar:?]
                        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104) ~[ColorMirai-4.0.5-all.jar:?]
                        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570) ~[ColorMirai-4.0.5-all.jar:?]
                        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:749) ~[ColorMirai-4.0.5-all.jar:?]
                        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677) ~[ColorMirai-4.0.5-all.jar:?]
                        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664) ~[ColorMirai-4.0.5-all.jar:?]
                Caused by: kotlinx.coroutines.JobCancellationException: Parent job is Cancelling
                Caused by: java.net.UnknownHostException: msfwifi.3g.qq.com: Temporary failure in name resolution
                        at java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method) ~[?:?]
                        at java.net.InetAddress$PlatformNameService.lookupAllHostAddr(InetAddress.java:933) ~[?:?]
                        at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1519) ~[?:?]
                        at java.net.InetAddress$NameServiceAddresses.get(InetAddress.java:852) ~[?:?]
                        at java.net.InetAddress.getAllByName0(InetAddress.java:1509) ~[?:?]
                        at java.net.InetAddress.getAllByName(InetAddress.java:1367) ~[?:?]
                        at java.net.InetAddress.getAllByName(InetAddress.java:1301) ~[?:?]
                        at java.net.InetAddress.getByName(InetAddress.java:1251) ~[?:?]
                        at io.netty.util.internal.SocketUtils$8.run(SocketUtils.java:156) ~[ColorMirai-4.0.5-all.jar:?]
                        at io.netty.util.internal.SocketUtils$8.run(SocketUtils.java:153) ~[ColorMirai-4.0.5-all.jar:?]
                        at java.security.AccessController.doPrivileged(AccessController.java:569) ~[?:?]
                        at io.netty.util.internal.SocketUtils.addressByName(SocketUtils.java:153) ~[ColorMirai-4.0.5-all.jar:?]
                        at io.netty.resolver.DefaultNameResolver.doResolve(DefaultNameResolver.java:41) ~[ColorMirai-4.0.5-all.jar:?]
                        at io.netty.resolver.SimpleNameResolver.resolve(SimpleNameResolver.java:61) ~[ColorMirai-4.0.5-all.jar:?]
                        at io.netty.resolver.SimpleNameResolver.resolve(SimpleNameResolver.java:53) ~[ColorMirai-4.0.5-all.jar:?]
                        at io.netty.resolver.InetSocketAddressResolver.doResolve(InetSocketAddressResolver.java:55) ~[ColorMirai-4.0.5-all.jar:?]
                        at io.netty.resolver.InetSocketAddressResolver.doResolve(InetSocketAddressResolver.java:31) ~[ColorMirai-4.0.5-all.jar:?]
                        at io.netty.resolver.AbstractAddressResolver.resolve(AbstractAddressResolver.java:106) ~[ColorMirai-4.0.5-all.jar:?]
                        at io.netty.bootstrap.Bootstrap.doResolveAndConnect0(Bootstrap.java:206) ~[ColorMirai-4.0.5-all.jar:?]
                        at io.netty.bootstrap.Bootstrap.access$000(Bootstrap.java:46) ~[ColorMirai-4.0.5-all.jar:?]
                        at io.netty.bootstrap.Bootstrap$1.operationComplete(Bootstrap.java:180) ~[ColorMirai-4.0.5-all.jar:?]
                        at io.netty.bootstrap.Bootstrap$1.operationComplete(Bootstrap.java:166) ~[ColorMirai-4.0.5-all.jar:?]
                        at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:578) ~[ColorMirai-4.0.5-all.jar:?]
                        at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:552) ~[ColorMirai-4.0.5-all.jar:?]
                        at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:491) ~[ColorMirai-4.0.5-all.jar:?]
                        at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:616) ~[ColorMirai-4.0.5-all.jar:?]
                        at io.netty.util.concurrent.DefaultPromise.setSuccess0(DefaultPromise.java:605) ~[ColorMirai-4.0.5-all.jar:?]
                        at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:104) ~[ColorMirai-4.0.5-all.jar:?]
                        at io.netty.channel.DefaultChannelPromise.trySuccess(DefaultChannelPromise.java:84) ~[ColorMirai-4.0.5-all.jar:?]
                        at io.netty.channel.AbstractChannel$AbstractUnsafe.safeSetSuccess(AbstractChannel.java:990) ~[ColorMirai-4.0.5-all.jar:?]
                        at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:516) ~[ColorMirai-4.0.5-all.jar:?]
                        at io.netty.channel.AbstractChannel$AbstractUnsafe.access$200(AbstractChannel.java:429) ~[ColorMirai-4.0.5-all.jar:?]
                        at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:486) ~[ColorMirai-4.0.5-all.jar:?]
                        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[ColorMirai-4.0.5-all.jar:?]
                        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) ~[ColorMirai-4.0.5-all.jar:?]
                        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[ColorMirai-4.0.5-all.jar:?]
                        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:503) ~[ColorMirai-4.0.5-all.jar:?]
                        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[ColorMirai-4.0.5-all.jar:?]
                        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[ColorMirai-4.0.5-all.jar:?]
                        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[ColorMirai-4.0.5-all.jar:?]
                        at java.lang.Thread.run(Thread.java:833) ~[?:?]

[00:40:07.932][ERROR]机器人启动失败
````

**Comment by Glucy-2** [comment]
网络问题
